# Generated by Django 5.2.4 on 2025-07-08 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, verbose_name='Название действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Действие администратора',
                'verbose_name_plural': 'Действия администратора',
                'ordering': ['action_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=100, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Лог администратора',
                'verbose_name_plural': 'Логи администратора',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100, verbose_name='Название разрешения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Разрешение администратора',
                'verbose_name_plural': 'Разрешения администратора',
                'ordering': ['permission_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('permissions', models.ManyToManyField(blank=True, to='universal_admin.adminpermission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'Роль администратора',
                'verbose_name_plural': 'Роли администратора',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universal_admin.adminrole', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя-администратора',
                'verbose_name_plural': 'Роли пользователей-администраторов',
                'unique_together': {('user', 'role')},
            },
        ),
    ] 