apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: veles-drive-postgres-pvc
  namespace: veles-drive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage-dynamic
