apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: veles-drive-static-pvc
  namespace: veles-drive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage-dynamic
