apiVersion: apps/v1
kind: Deployment
metadata:
  name: veles-drive-frontend
  namespace: veles-drive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: veles-drive-frontend
  template:
    metadata:
      labels:
        app: veles-drive-frontend
    spec:
      containers:
      - name: frontend
        image: alsx12/veles-drive-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: NODE_ENV
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: REACT_APP_API_URL
        - name: REACT_APP_WS_URL
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: REACT_APP_WS_URL
        - name: REACT_APP_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: REACT_APP_DOMAIN
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
