apiVersion: batch/v1
kind: Job
metadata:
  name: veles-drive-init-db
  namespace: veles-drive
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: alsx12/veles-drive-backend:latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Waiting for database to be ready..."
          while ! pg_isready -h veles-drive-postgres -U veles_user -d veles_drive; do
            sleep 2
          done
          echo "Database is ready!"
          
          echo "Running migrations..."
          python manage.py migrate
          
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          
          echo "Creating superuser if not exists..."
          python manage.py shell -c "
          from django.contrib.auth import get_user_model
          User = get_user_model()
          if not User.objects.filter(username='admin').exists():
              User.objects.create_superuser('admin', 'admin@veles-drive.ru', 'veles_admin_2024')
              print('Superuser created')
          else:
              print('Superuser already exists')
          "
          
          echo "Database initialization completed!"
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: DJANGO_SETTINGS_MODULE
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: veles-drive-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: veles-drive-config
              key: DATABASE_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: veles-drive-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: static-storage
          mountPath: /app/staticfiles
        - name: media-storage
          mountPath: /app/mediafiles
      volumes:
      - name: static-storage
        persistentVolumeClaim:
          claimName: veles-drive-static-pvc
      - name: media-storage
        persistentVolumeClaim:
          claimName: veles-drive-media-pvc
      restartPolicy: OnFailure
  backoffLimit: 3
