# Generated by Django 5.2.4 on 2025-07-07 20:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_remove_company_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-rating', '-created_at'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='companyfeature',
            options={'ordering': ['name'], 'verbose_name': 'Характеристика компании', 'verbose_name_plural': 'Характеристики компаний'},
        ),
        migrations.AlterModelOptions(
            name='companyimage',
            options={'ordering': ['-is_main', '-created_at'], 'verbose_name': 'Изображение компании', 'verbose_name_plural': 'Изображения компаний'},
        ),
        migrations.AlterModelOptions(
            name='companyschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Расписание работы', 'verbose_name_plural': 'Расписания работы'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='Неизвестный адрес', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='Без описания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверена'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Неизвестно', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.ImageField(upload_to='companies/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='close_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='open_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
